# Generated by Django 6.0 on 2025-12-31 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidade", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="phone",
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
